### ISSUE TITLE
Design config file structure

### ISSUE THREAD

**Issue by chrisrohr** [fortitudetec/sprawl#1]
First blush:

```yaml
name: first-service
description: This is our first service
language: Java
datastores:
  - Postgres
messageTypesProduced:
  - HelloThere
  - Status
messageTypesConsumed:
  - ByeBye
  - DoIt
restDependencies:
  - second-service
  - third-service
```

Required items would be name, description, language.  Everything else optional.
